[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
tic_tac_toe = "AmzgW58Wn82iRhxKTFSMkjKDKw2B1ojLEi1bVykLzRyS"

[programs.localnet]
tic_tac_toe = "Ajc8jZmvtHKnV5DFAuwzv7mEfbxnhP2HUYm6mAN7Y86J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
